// ─── Liverpool FC Player Data (2025-26 Season · Updated May 24, 2026) ──────
// Extracted from App.jsx — single source of truth for player, news, and RSS data

// Statuses: "fit" | "injured" | "doubtful" | "recovering"
// injuryNote: short description shown on card when not fit
// Optional: returningFromInjury: { matchesBackIncludingThis: 1|2 }
//   — added by skill when a player returns from 3+ week absence, removed after 2 matches back
// Optional: outSince: "YYYY-MM-DD"
//   — earliest date the player has been unavailable; used by buildPlayerLast5
//     to flag missed matches as "-" instead of inheriting the team's W/D/L
// Optional: recentPlayedDates: ["YYYY-MM-DD", ...]
//   — for fringe/academy players (≤6 senior apps) who DID start a recent match
//     and should show that result instead of a blanket "-"
export const PLAYERS = [
  // ── Goalkeepers ───────────────────────────────────────────────────────────
  {
    id: 1, name: "Alisson Becker", number: 1, position: "GK", nationality: "🇧🇷 Brazil", age: 33, appearances: 32, goals: 0, assists: 0, cleanSheets: 10, xG: 0, tacklesPer90: 0, passCompletion: 82, progressiveCarries: 0.2, form: 6.5, status: "fit", injuryNote: "Mon Jun 8 — the No. 1 question is settled: per Brazilian sources, Alisson has turned down Juventus to stay at Anfield at least another season, his extension already triggered. He heads to the World Cup as Brazil's first choice and returns as the unarguable starter — the knock-on falling on Mamardashvili, now the likelier to leave on loan", image: "https://r2.thesportsdb.com/images/media/player/cutout/8amq961757087569.png",
    physical: { height: 191, weight: 91, pace: 48, acceleration: 45, sprintSpeed: 50 },
    career: [
      { years: "2008-2013", club: "Internacional", fee: null, type: "youth" },
      { years: "2013-2016", club: "Internacional", fee: null, type: "senior" },
      { years: "2016-2018", club: "Roma", fee: "€7.5M", type: "senior" },
      { years: "2018-", club: "Liverpool", fee: "€62.5M", type: "senior" },
    ],
  },
  {
    id: 2, name: "Giorgi Mamardashvili", number: 25, position: "GK", nationality: "🇬🇪 Georgia", age: 25, appearances: 19, goals: 0, assists: 0, cleanSheets: 5, xG: 0, tacklesPer90: 0, passCompletion: 76, progressiveCarries: 0.1, form: 6.2, status: "fit", injuryNote: "Mon Jun 8 — a loan is now the likeliest route: with Alisson having chosen to stay, the £29m Valencia signing looks ticketed for game time elsewhere rather than a second year of understudy minutes. The club's longer-term thinking still circles Porto's Diogo Costa and his €60m release clause", image: "https://r2.thesportsdb.com/images/media/player/cutout/3yoja81757088527.png",
    physical: { height: 197, weight: 93, pace: 42, acceleration: 40, sprintSpeed: 44 },
    career: [
      { years: "2017-2021", club: "Dinamo Tbilisi", fee: null, type: "youth" },
      { years: "2021-2022", club: "Dinamo Tbilisi", fee: null, type: "senior" },
      { years: "2022-2025", club: "Valencia", fee: "€800K", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€30M", type: "senior" },
    ],
  },

  // ── Defenders ─────────────────────────────────────────────────────────────
  {
    id: 3, name: "Virgil van Dijk", number: 4, position: "DEF", nationality: "🇳🇱 Netherlands", age: 34, appearances: 43, goals: 6, assists: 1, cleanSheets: 11, xG: 3.2, tacklesPer90: 1.2, passCompletion: 92, progressiveCarries: 0.8, form: 7.4, status: "fit", injuryNote: "Mon May 25 — season over: the captain closes a hard campaign with his own standards intact, under contract to June 2027. He will be central both to the end-of-season review and to whatever shape the summer rebuild takes around him", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p97032.png",
    physical: { height: 193, weight: 92, pace: 72, acceleration: 68, sprintSpeed: 75 },
    career: [
      { years: "2011-2013", club: "Groningen", fee: null, type: "youth" },
      { years: "2013-2015", club: "Celtic", fee: "€2.6M", type: "senior" },
      { years: "2015-2018", club: "Southampton", fee: "€13M", type: "senior" },
      { years: "2018-", club: "Liverpool", fee: "€84.5M", type: "senior" },
    ],
  },
  {
    id: 4, name: "Ibrahima Konaté", number: 5, position: "DEF", nationality: "🇫🇷 France", age: 27, appearances: 40, goals: 2, assists: 0, cleanSheets: 10, xG: 1.5, tacklesPer90: 1.8, passCompletion: 88, progressiveCarries: 0.5, form: 6.4, status: "fit", injuryNote: "Tue Jun 9 — now only a photograph away: with Pérez's Bernabéu re-election having cleared the last condition, the four-year free transfer to Real Madrid (~€24m gross a season, to 2030) is sealed and awaiting its formal unveiling. A France international leaves for nothing — the cost of a stalled extension — and the right-sided vacancy he leaves is the one the £40m Ordóñez bid is built to fill", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p204716.png",
    physical: { height: 194, weight: 95, pace: 78, acceleration: 76, sprintSpeed: 80 },
    career: [
      { years: "2014-2017", club: "Sochaux", fee: null, type: "youth" },
      { years: "2017-2021", club: "RB Leipzig", fee: "€15M", type: "senior" },
      { years: "2021-", club: "Liverpool", fee: "€40M", type: "senior" },
    ],
  },
  {
    id: 5, name: "Joe Gomez", number: 2, position: "DEF", nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", age: 28, appearances: 19, goals: 0, assists: 1, cleanSheets: 5, xG: 0.2, tacklesPer90: 1.3, passCompletion: 88, progressiveCarries: 1.5, form: 5.9, status: "fit", injuryNote: "Sat May 30 — caught between two truths: with Hughes hunting two centre-backs the academy product is depth Liverpool may suddenly need, yet at twelve months left and with a Serie A move openly canvassed he is also among the likeliest sell-to-buy departures. A hard call — keep the cover or bank the fee", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p171287.png",
    physical: { height: 188, weight: 80, pace: 76, acceleration: 78, sprintSpeed: 74 },
    career: [
      { years: "2012-2015", club: "Charlton Athletic", fee: null, type: "youth" },
      { years: "2015-", club: "Liverpool", fee: "€4.7M", type: "senior" },
    ],
  },
  {
    id: 6, name: "Andy Robertson", number: 26, position: "DEF", nationality: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland", age: 32, appearances: 30, goals: 1, assists: 3, cleanSheets: 8, xG: 0.6, tacklesPer90: 2.3, passCompletion: 83, progressiveCarries: 4.4, form: 6.7, status: "fit", injuryNote: "Sat May 30 — the Tottenham move is done bar the unveiling: a free transfer to De Zerbi's side, a late Juventus hijack rebuffed. Nine years, two title runs and one of the great value signings of the modern era walk out of Anfield; the left-back slot passes unarguably to Milos Kerkez after his tough first season", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p122798.png",
    physical: { height: 178, weight: 70, pace: 79, acceleration: 81, sprintSpeed: 77 },
    career: [
      { years: "2010-2013", club: "Queen's Park", fee: null, type: "senior" },
      { years: "2013-2014", club: "Dundee United", fee: "Free", type: "senior" },
      { years: "2014-2017", club: "Hull City", fee: "€3.4M", type: "senior" },
      { years: "2017-", club: "Liverpool", fee: "€9.3M", type: "senior" },
    ],
  },
  {
    id: 7, name: "Milos Kerkez", number: 6, position: "DEF", nationality: "🇭🇺 Hungary", age: 22, appearances: 38, goals: 2, assists: 2, cleanSheets: 7, xG: 0.4, tacklesPer90: 2.0, passCompletion: 80, progressiveCarries: 4.8, form: 6.8, status: "fit", injuryNote: "Mon May 25 — season over: a difficult first season after his £45m move, the Hungarian drawing criticism for an uneasy adaptation at left-back. With Robertson gone, the left-back job is now unambiguously his to hold", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p544877.png",
    physical: { height: 185, weight: 78, pace: 82, acceleration: 84, sprintSpeed: 80 },
    career: [
      { years: "2018-2021", club: "Györ", fee: null, type: "youth" },
      { years: "2021-2022", club: "AC Milan Primavera", fee: "€400K", type: "youth" },
      { years: "2022-2023", club: "AZ Alkmaar", fee: "€2M", type: "senior" },
      { years: "2023-2025", club: "Bournemouth", fee: "€16M", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€45M", type: "senior" },
    ],
  },
  {
    id: 8, name: "Conor Bradley", number: 12, position: "DEF", nationality: "🇬🇧 N. Ireland", age: 22, appearances: 16, goals: 0, assists: 2, cleanSheets: 4, xG: 0.8, tacklesPer90: 2.6, passCompletion: 84, progressiveCarries: 5.1, form: 7.3, status: "injured", outSince: "2026-01-09", injuryNote: "Thu May 28 — a pre-season doubt now: four and a half months after the knee gave way at Arsenal, he is back on load-bearing gym work at the AXA centre, but Slot has called the case 'complicated' and there is 'no timeline.' Northern Ireland's Michael O'Neill says he is 'doing well' while keeping the detail confidential", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p492777.png",
    physical: { height: 180, weight: 72, pace: 83, acceleration: 85, sprintSpeed: 82 },
    career: [
      { years: "2019-2022", club: "Liverpool Academy", fee: null, type: "youth" },
      { years: "2023", club: "Bolton Wanderers (loan)", fee: null, type: "senior" },
      { years: "2022-", club: "Liverpool", fee: null, type: "senior" },
    ],
  },
  {
    id: 9, name: "Jeremie Frimpong", number: 30, position: "DEF", nationality: "🇳🇱 Netherlands", age: 24, appearances: 35, goals: 1, assists: 4, cleanSheets: 7, xG: 0.9, tacklesPer90: 2.2, passCompletion: 83, progressiveCarries: 3.8, form: 6.4, status: "fit", injuryNote: "Fri May 29 — left out of the Netherlands' World Cup squad, Koeman citing 'the pattern of this season that he has been injured regularly.' A stop-start debut campaign disrupted by muscular problems cost him 35-cap rhythm and now a summer tournament; an uninterrupted pre-season is everything before the 2026-27 push", image: "https://r2.thesportsdb.com/images/media/player/cutout/ehf7fi1757088020.png",
    physical: { height: 171, weight: 66, pace: 91, acceleration: 93, sprintSpeed: 89 },
    career: [
      { years: "2017-2019", club: "Manchester City Academy", fee: null, type: "youth" },
      { years: "2019-2021", club: "Celtic", fee: "€350K", type: "senior" },
      { years: "2021-2025", club: "Bayer Leverkusen", fee: "€11M", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€40M", type: "senior" },
    ],
  },
  {
    id: 10, name: "Giovanni Leoni", number: 33, position: "DEF", nationality: "🇮🇹 Italy", age: 18, appearances: 1, goals: 0, assists: 0, cleanSheets: 0, xG: 0, tacklesPer90: 0, passCompletion: 0, progressiveCarries: 0, form: 0, status: "injured", outSince: "2025-09-15", injuryNote: "Mon May 25 — torn ACL last September; the long rehabilitation continues, with a return targeted for the 2026-27 season", image: "https://r2.thesportsdb.com/images/media/player/cutout/8aws9t1766829004.png",
    physical: { height: 190, weight: 82, pace: 70, acceleration: 68, sprintSpeed: 72 },
    career: [
      { years: "2020-2023", club: "Padova", fee: null, type: "youth" },
      { years: "2023-2024", club: "Sampdoria", fee: "€1.5M", type: "senior" },
      { years: "2024-2025", club: "Genoa", fee: "€4M", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€15M", type: "senior" },
    ],
  },
  {
    id: 11, name: "Jérémy Jacquet", number: 23, position: "DEF", nationality: "🇫🇷 France", age: 20, appearances: 6, goals: 0, assists: 0, cleanSheets: 2, xG: 0.1, tacklesPer90: 1.6, passCompletion: 86, progressiveCarries: 1.4, form: 6.6, status: "fit", injuryNote: null, image: "https://r2.thesportsdb.com/images/media/player/cutout/d6qx171766136993.png",
    physical: { height: 184, weight: 76, pace: 74, acceleration: 72, sprintSpeed: 75 },
    career: [
      { years: "2019-2024", club: "Lyon Academy", fee: null, type: "youth" },
      { years: "2024-2025", club: "Lyon", fee: null, type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€8M", type: "senior" },
    ],
  },
  {
    id: 12, name: "Ifeanyi Ndukwe", number: 53, position: "DEF", nationality: "🇳🇬 Nigeria", age: 19, appearances: 2, goals: 0, assists: 0, cleanSheets: 1, xG: 0, tacklesPer90: 1.2, passCompletion: 82, progressiveCarries: 0.8, form: 6.3, status: "fit", injuryNote: null, image: "https://r2.thesportsdb.com/images/media/player/cutout/iagott1769030864.png",
    physical: { height: 186, weight: 78, pace: 72, acceleration: 70, sprintSpeed: 73 },
    career: [
      { years: "2021-2025", club: "Liverpool Academy", fee: null, type: "youth" },
      { years: "2025-", club: "Liverpool", fee: null, type: "senior" },
    ],
  },

  // ── Midfielders ───────────────────────────────────────────────────────────
  {
    id: 13, name: "Alexis Mac Allister", number: 10, position: "MID", nationality: "🇦🇷 Argentina", age: 27, appearances: 41, goals: 2, assists: 4, cleanSheets: null, xG: 1.9, tacklesPer90: 1.9, passCompletion: 90, progressiveCarries: 1.4, form: 6.7, status: "fit", injuryNote: "Tue Jun 9 — still pulled between the two Madrids: Real and Atlético both remain linked with the Argentine, who has no new-contract talks underway as he enters the final two years of his deal — pointed against Gravenberch's fresh extension. His father Carlos again denied a formal approach while conceding the player views La Liga warmly; flagged internally as sellable near €120m, he is the sell-to-buy fuel a midfield reshape would run on", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p243016.png",
    physical: { height: 174, weight: 72, pace: 68, acceleration: 70, sprintSpeed: 66 },
    career: [
      { years: "2013-2019", club: "Argentinos Juniors", fee: null, type: "youth" },
      { years: "2019-2023", club: "Brighton & Hove Albion", fee: "€8M", type: "senior" },
      { years: "2023-", club: "Liverpool", fee: "€40M", type: "senior" },
    ],
  },
  {
    id: 14, name: "Ryan Gravenberch", number: 38, position: "MID", nationality: "🇳🇱 Netherlands", age: 23, appearances: 41, goals: 6, assists: 5, cleanSheets: null, xG: 3.1, tacklesPer90: 2.8, passCompletion: 91, progressiveCarries: 3.2, form: 7.2, status: "fit", injuryNote: "Mon May 25 — season over: Liverpool's most consistent midfielder across a turbulent campaign, and an obvious building block for whatever the summer's decisions construct next", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p441266.png",
    physical: { height: 190, weight: 80, pace: 74, acceleration: 76, sprintSpeed: 72 },
    career: [
      { years: "2010-2018", club: "Ajax Academy", fee: null, type: "youth" },
      { years: "2018-2022", club: "Ajax", fee: null, type: "senior" },
      { years: "2022-2023", club: "Bayern Munich", fee: "€18.5M", type: "senior" },
      { years: "2023-", club: "Liverpool", fee: "€40M", type: "senior" },
    ],
  },
  {
    id: 15, name: "Dominik Szoboszlai", number: 8, position: "MID", nationality: "🇭🇺 Hungary", age: 25, appearances: 48, goals: 12, assists: 9, cleanSheets: null, xG: 6.2, tacklesPer90: 2.1, passCompletion: 86, progressiveCarries: 2.8, form: 7.3, status: "fit", injuryNote: "Mon May 25 — season over: closes a heavy-minutes season of 48 appearances as a midfield mainstay; a contract extension is still expected to be agreed over the summer", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p424876.png",
    physical: { height: 186, weight: 79, pace: 76, acceleration: 78, sprintSpeed: 74 },
    career: [
      { years: "2015-2018", club: "Liefering", fee: null, type: "youth" },
      { years: "2018-2020", club: "Red Bull Salzburg", fee: null, type: "senior" },
      { years: "2020-2023", club: "RB Leipzig", fee: "€20M", type: "senior" },
      { years: "2023-", club: "Liverpool", fee: "€70M", type: "senior" },
    ],
  },
  {
    id: 16, name: "Curtis Jones", number: 17, position: "MID", nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", age: 25, appearances: 28, goals: 2, assists: 4, cleanSheets: null, xG: 1.8, tacklesPer90: 1.5, passCompletion: 86, progressiveCarries: 3.9, form: 6.9, status: "fit", injuryNote: "Tue Jun 9 — the talks intensify: Inter have lined up a fresh meeting with Richard Hughes to push the deal toward the line near €25m, after their €20m opener was rejected. Jones is reported to be prioritising San Siro and ready to snub Aston Villa; among the names Iraola may move on, his sale would book as near-pure profit, with the window opening June 15", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p206915.png",
    physical: { height: 182, weight: 74, pace: 72, acceleration: 74, sprintSpeed: 70 },
    career: [
      { years: "2010-2019", club: "Liverpool Academy", fee: null, type: "youth" },
      { years: "2019-", club: "Liverpool", fee: null, type: "senior" },
    ],
  },
  {
    id: 17, name: "Wataru Endo", number: 3, position: "MID", nationality: "🇯🇵 Japan", age: 33, appearances: 14, goals: 0, assists: 1, cleanSheets: null, xG: 0.3, tacklesPer90: 3.1, passCompletion: 87, progressiveCarries: 1.2, form: 6.2, status: "fit", outSince: "2026-02-12", injuryNote: "Thu Jun 4 — the rehab race is won: named in Japan's World Cup squad and set to captain them in America, four months after rupturing ankle ligaments at Sunderland. He returns to Anfield pre-season as a likely summer sale, his squad role reduced — but the comeback itself is complete", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p158983.png",
    physical: { height: 178, weight: 76, pace: 60, acceleration: 58, sprintSpeed: 62 },
    career: [
      { years: "2010-2012", club: "Yokohama F. Marinos", fee: null, type: "youth" },
      { years: "2012-2015", club: "Shonan Bellmare", fee: null, type: "senior" },
      { years: "2015-2018", club: "Urawa Red Diamonds", fee: null, type: "senior" },
      { years: "2018-2019", club: "Sint-Truiden", fee: "€300K", type: "senior" },
      { years: "2019-2023", club: "VfB Stuttgart", fee: "€1.5M", type: "senior" },
      { years: "2023-", club: "Liverpool", fee: "€19.2M", type: "senior" },
    ],
  },
  {
    id: 18, name: "Florian Wirtz", number: 7, position: "MID", nationality: "🇩🇪 Germany", age: 23, appearances: 33, goals: 6, assists: 6, cleanSheets: null, xG: 4.9, tacklesPer90: 1.0, passCompletion: 87, progressiveCarries: 4.1, form: 7.1, status: "fit", injuryNote: "Mon May 25 — season over: an injury-disrupted, awkward first season at Liverpool — the £115m playmaker shared just 117 minutes on the pitch with Isak and Ekitike all year. A clean pre-season is everything now", image: "https://r2.thesportsdb.com/images/media/player/cutout/8t6bzo1757088899.png",
    physical: { height: 176, weight: 70, pace: 78, acceleration: 82, sprintSpeed: 75 },
    career: [
      { years: "2015-2020", club: "1. FC Köln Academy", fee: null, type: "youth" },
      { years: "2020-2025", club: "Bayer Leverkusen", fee: "€200K", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€115M", type: "senior" },
    ],
  },
  {
    id: 19, name: "Stefan Bajcetic", number: 43, position: "MID", nationality: "🇪🇸 Spain", age: 21, appearances: 0, goals: 0, assists: 0, cleanSheets: null, xG: 0, tacklesPer90: 0, passCompletion: 0, progressiveCarries: 0, form: 0, status: "injured", outSince: "2025-08-01", injuryNote: "Mon May 25 — recurring hamstring trouble cost him the entire 2025-26 season; a make-or-break summer lies ahead", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p535928.png",
    physical: { height: 185, weight: 75, pace: 68, acceleration: 66, sprintSpeed: 70 },
    career: [
      { years: "2017-2020", club: "Celta Vigo Academy", fee: null, type: "youth" },
      { years: "2020-2022", club: "Liverpool Academy", fee: "€250K", type: "youth" },
      { years: "2022-", club: "Liverpool", fee: null, type: "senior" },
    ],
  },
  {
    id: 20, name: "Trey Nyoni", number: 42, position: "MID", nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", age: 17, appearances: 5, goals: 0, assists: 0, cleanSheets: null, xG: 0.2, tacklesPer90: 1.0, passCompletion: 84, progressiveCarries: 2.8, form: 6.0, status: "fit", injuryNote: null, image: "https://backend.liverpoolfc.com/sites/default/files/styles/xs/public/2025-08/trey-nyoni-2025-26-bodyshot_c04372ac9100f85a5647a0cd12e323c0.webp?itok=nTrwzG0A",
    physical: { height: 178, weight: 68, pace: 74, acceleration: 76, sprintSpeed: 72 },
    career: [
      { years: "2020-2023", club: "Leicester City Academy", fee: null, type: "youth" },
      { years: "2023-", club: "Liverpool", fee: "€300K", type: "youth" },
    ],
  },

  // ── Forwards ──────────────────────────────────────────────────────────────
  {
    id: 21, name: "Mohamed Salah", number: 11, position: "FWD", nationality: "🇪🇬 Egypt", age: 33, appearances: 39, goals: 10, assists: 10, cleanSheets: null, xG: 7.0, tacklesPer90: 0.6, passCompletion: 82, progressiveCarries: 3.5, form: 7.0, status: "fit", injuryNote: "Tue Jun 9 — the goodbye plays on through the tournament: Egypt's captain at the 2026 World Cup, the departing forward will not settle his club future until it is done. The contract lapses June 30; the market has reordered around the wait, Turkey now ahead of Saudi Arabia and MLS with a sentimental Italian return floated third. A nine-year story keeps its final line in pencil while its author plays one more summer in green", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p118748.png",
    physical: { height: 175, weight: 71, pace: 86, acceleration: 88, sprintSpeed: 85 },
    career: [
      { years: "2010-2012", club: "El Mokawloon", fee: null, type: "senior" },
      { years: "2012-2016", club: "Basel", fee: "€2.5M", type: "senior" },
      { years: "2014-2015", club: "Chelsea", fee: "€16M", type: "senior" },
      { years: "2015-2016", club: "Fiorentina (loan)", fee: null, type: "senior" },
      { years: "2016-2017", club: "Roma (loan/permanent)", fee: "€17M", type: "senior" },
      { years: "2017-", club: "Liverpool", fee: "€42M", type: "senior" },
    ],
  },
  {
    id: 22, name: "Cody Gakpo", number: 18, position: "FWD", nationality: "🇳🇱 Netherlands", age: 25, appearances: 39, goals: 9, assists: 6, cleanSheets: null, xG: 7.1, tacklesPer90: 0.8, passCompletion: 81, progressiveCarries: 2.5, form: 6.8, status: "fit", injuryNote: "Tue Jun 9 — the request now doubles as leverage: having asked to leave rather than fight Rio Ngumoha for the left wing under Iraola, the Dutch forward is reported as a possible makeweight in a swap to bring Diomandé from Leipzig — even as Tottenham stay strongly keen on a straight sale near €45m. A nine-goal season turning into a bargaining chip in the deal built to replace him", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p243298.png",
    physical: { height: 189, weight: 82, pace: 80, acceleration: 82, sprintSpeed: 78 },
    career: [
      { years: "2007-2018", club: "PSV Academy", fee: null, type: "youth" },
      { years: "2018-2023", club: "PSV Eindhoven", fee: null, type: "senior" },
      { years: "2023-", club: "Liverpool", fee: "€42M", type: "senior" },
    ],
  },
  {
    id: 23, name: "Alexander Isak", number: 9, position: "FWD", nationality: "🇸🇪 Sweden", age: 26, appearances: 18, goals: 9, assists: 2, cleanSheets: null, xG: 9.6, tacklesPer90: 0.4, passCompletion: 76, progressiveCarries: 3.2, form: 7.5, status: "fit", injuryNote: "Mon May 25 — season over: an injury-wrecked debut season — a string of setbacks limited the £100m striker to a handful of starts and never let Slot's intended front three settle. A full summer to reset", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p219168.png",
    physical: { height: 192, weight: 80, pace: 82, acceleration: 80, sprintSpeed: 84 },
    career: [
      { years: "2014-2017", club: "AIK", fee: null, type: "youth" },
      { years: "2017-2019", club: "Borussia Dortmund", fee: "€9M", type: "senior" },
      { years: "2019-2022", club: "Real Sociedad", fee: "€6.5M", type: "senior" },
      { years: "2022-2025", club: "Newcastle United", fee: "€70M", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€100M", type: "senior" },
    ],
  },
  {
    id: 24, name: "Hugo Ekitike", number: 22, position: "FWD", nationality: "🇫🇷 France", age: 23, appearances: 41, goals: 18, assists: 5, cleanSheets: null, xG: 14.2, tacklesPer90: 0.4, passCompletion: 78, progressiveCarries: 2.1, form: 7.3, status: "injured", outSince: "2026-04-15", injuryNote: "Mon May 25 — ruptured Achilles (April 14 vs PSG): the scan confirmed a 9-12 month absence, ruling him out of the rest of 2025-26 and France's 2026 World Cup", image: "https://r2.thesportsdb.com/images/media/player/cutout/8za47v1757087851.png",
    physical: { height: 190, weight: 78, pace: 83, acceleration: 85, sprintSpeed: 82 },
    career: [
      { years: "2016-2020", club: "Reims Academy", fee: null, type: "youth" },
      { years: "2020-2022", club: "Reims", fee: null, type: "senior" },
      { years: "2022-2023", club: "PSG (loan)", fee: null, type: "senior" },
      { years: "2023-2025", club: "Eintracht Frankfurt", fee: "€16.5M", type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "€55M", type: "senior" },
    ],
  },
  {
    id: 25, name: "Rio Ngumoha", number: 48, position: "FWD", nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", age: 17, appearances: 13, goals: 2, assists: 2, cleanSheets: null, xG: 1.4, tacklesPer90: 0.3, passCompletion: 78, progressiveCarries: 3.5, form: 7.3, status: "fit", recentPlayedDates: ["2026-04-25", "2026-05-03", "2026-05-09", "2026-05-15"], injuryNote: "Mon Jun 8 — still untouchable: Fabrizio Romano restates the 17-year-old has 'no chance' of leaving as Bayern keep him on their list after missing Anthony Gordon, with no formal contact made — Liverpool's position unmoved. With Gakpo now asking to leave, the left flank the youngest goalscorer in the club's history would inherit looks more his than ever", image: "https://r2.thesportsdb.com/images/media/player/cutout/ay5j761773955893.png",
    physical: { height: 175, weight: 68, pace: 85, acceleration: 88, sprintSpeed: 83 },
    career: [
      { years: "2019-2024", club: "Chelsea Academy", fee: null, type: "youth" },
      { years: "2024-", club: "Liverpool", fee: "Compensation", type: "youth" },
    ],
  },
  {
    id: 26, name: "Federico Chiesa", number: 14, position: "FWD", nationality: "🇮🇹 Italy", age: 28, appearances: 12, goals: 1, assists: 1, cleanSheets: null, xG: 1.5, tacklesPer90: 0.6, passCompletion: 80, progressiveCarries: 2.2, form: 6.0, status: "fit", injuryNote: "Mon May 25 — season over: a bit-part year for the Italian, who features prominently on summer clear-out lists — an exit looks the likeliest outcome", image: "https://r2.thesportsdb.com/images/media/player/cutout/idecla1757087689.png",
    physical: { height: 175, weight: 70, pace: 84, acceleration: 86, sprintSpeed: 82 },
    career: [
      { years: "2016-2020", club: "Fiorentina", fee: null, type: "senior" },
      { years: "2020-2024", club: "Juventus", fee: "€40M", type: "senior" },
      { years: "2024-", club: "Liverpool", fee: "€12M", type: "senior" },
    ],
  },

  // ── Late additions ────────────────────────────────────────────────────────
  {
    id: 27, name: "Freddie Woodman", number: 28, position: "GK", nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", age: 29, appearances: 2, goals: 0, assists: 0, cleanSheets: 0, xG: 0, tacklesPer90: 0, passCompletion: 78, progressiveCarries: 0.1, form: 7.4, status: "fit", recentPlayedDates: ["2026-04-25", "2026-05-03"], injuryNote: "Mon May 25 — season over: third-choice goalkeeper across the campaign, with two Premier League starts. A dependable squad option as the goalkeeping picture is reviewed", image: "https://resources.premierleague.com/premierleague/photos/players/110x140/p155503.png",
    physical: { height: 188, weight: 82, pace: 47, acceleration: 45, sprintSpeed: 50 },
    career: [
      { years: "2009-2013", club: "Crystal Palace Academy", fee: null, type: "youth" },
      { years: "2013-2015", club: "Newcastle Academy", fee: null, type: "youth" },
      { years: "2015-2022", club: "Newcastle United", fee: null, type: "senior" },
      { years: "2015-2016", club: "Hartlepool (loan)", fee: null, type: "senior" },
      { years: "2016", club: "Crawley Town (loan)", fee: null, type: "senior" },
      { years: "2017", club: "Kilmarnock (loan)", fee: null, type: "senior" },
      { years: "2017-2018", club: "Aberdeen (loan)", fee: null, type: "senior" },
      { years: "2018-2021", club: "Swansea City (loan)", fee: null, type: "senior" },
      { years: "2021-2022", club: "AFC Bournemouth (loan)", fee: null, type: "senior" },
      { years: "2022-2025", club: "Preston North End", fee: null, type: "senior" },
      { years: "2025-", club: "Liverpool", fee: "Free", type: "senior" },
    ],
  },
];

// ─── RSS Feed Sources ───────────────────────────────────────────────────────
export const RSS_FEEDS = [
  { name: "Rousing The Kop", url: "https://www.rousingthekop.com/feed/", category: "fan", color: "#C8102E" },
  { name: "BBC Sport - Liverpool", url: "http://feeds.bbci.co.uk/sport/football/teams/liverpool/rss.xml", category: "major", color: "#BB1919" },
  { name: "Sky Sports - Liverpool", url: "https://www.skysports.com/rss/12040", category: "major", color: "#E10600" },
  { name: "This Is Anfield", url: "https://www.thisisanfield.com/feed/", category: "fan", color: "#D4213D" },
  { name: "Empire of the Kop", url: "https://www.empireofthekop.com/feed/", category: "fan", color: "#8B0000" },
  { name: "The Anfield Wrap", url: "https://www.theanfieldwrap.com/feed/", category: "fan", color: "#B22222" },
  { name: "ESPN FC - Liverpool", url: "https://www.espn.com/espn/rss/soccer/news", category: "major", color: "#CC0000" },
];

// ─── Team Logos ────────────────────────────────────────────────────────────
// PL crests via premierleague.com CDN, UCL teams via img.uefa.com
export const TEAM_LOGOS = {
  "Liverpool":      "https://resources.premierleague.com/premierleague/badges/50/t14.png",
  "Galatasaray":    "https://img.uefa.com/imgml/TP/teams/logos/50x50/50137.png",
  "Tottenham":      "https://resources.premierleague.com/premierleague/badges/50/t6.png",
  "Wolves":         "https://resources.premierleague.com/premierleague/badges/50/t39.png",
  "West Ham":       "https://resources.premierleague.com/premierleague/badges/50/t21.png",
  "Nott'm Forest":  "https://resources.premierleague.com/premierleague/badges/50/t17.png",
  "Brighton":       "https://resources.premierleague.com/premierleague/badges/50/t36.png",
  "Sunderland":     "https://resources.premierleague.com/premierleague/badges/50/t56.png",
  "Man City":       "https://resources.premierleague.com/premierleague/badges/50/t43.png",
  "Newcastle":      "https://resources.premierleague.com/premierleague/badges/50/t4.png",
  "Bournemouth":    "https://resources.premierleague.com/premierleague/badges/50/t91.png",
  "Burnley":        "https://resources.premierleague.com/premierleague/badges/50/t90.png",
  "Leeds":          "https://resources.premierleague.com/premierleague/badges/50/t2.png",
  "Barnsley":       "https://upload.wikimedia.org/wikipedia/en/c/c9/Barnsley_FC.svg",
  "Arsenal":        "https://resources.premierleague.com/premierleague/badges/50/t3.png",
  "PSG":            "https://img.uefa.com/imgml/TP/teams/logos/50x50/52747.png",
  "Brighton & Hove Albion": "https://resources.premierleague.com/premierleague/badges/50/t36.png",
  "Fulham":         "https://resources.premierleague.com/premierleague/badges/50/t54.png",
  "Everton":        "https://resources.premierleague.com/premierleague/badges/50/t11.png",
  "Crystal Palace":  "https://resources.premierleague.com/premierleague/badges/50/t31.png",
  "Manchester City": "https://resources.premierleague.com/premierleague/badges/50/t43.png",
  "Manchester United": "https://resources.premierleague.com/premierleague/badges/50/t1.png",
  "Chelsea":         "https://resources.premierleague.com/premierleague/badges/50/t8.png",
  "Aston Villa":     "https://resources.premierleague.com/premierleague/badges/50/t7.png",
  "Brentford":       "https://resources.premierleague.com/premierleague/badges/50/t94.png",
  // Transfer-target clubs
  "Bayer Leverkusen": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52867.png",
  "RB Leipzig":       "https://img.uefa.com/imgml/TP/teams/logos/50x50/2603790.png",
  "Real Sociedad":    "https://img.uefa.com/imgml/TP/teams/logos/50x50/50080.png",
  "Porto":            "https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg",
  "Bayern Munich":    "https://img.uefa.com/imgml/TP/teams/logos/50x50/50037.png",
  "Real Madrid":      "https://img.uefa.com/imgml/TP/teams/logos/50x50/50051.png",
  "Inter Milan":      "https://img.uefa.com/imgml/TP/teams/logos/50x50/50138.png",
  "Juventus":         "https://img.uefa.com/imgml/TP/teams/logos/50x50/50139.png",
  "Atlético Madrid":  "https://img.uefa.com/imgml/TP/teams/logos/50x50/50124.png",
  "Rennes":           "https://img.uefa.com/imgml/TP/teams/logos/50x50/50097.png",
  "Rennes (loan)":    "https://img.uefa.com/imgml/TP/teams/logos/50x50/50097.png",
  "Club Brugge":      "https://upload.wikimedia.org/wikipedia/en/d/d0/Club_Brugge_KV_logo.svg",
  "Sporting CP":      "https://img.uefa.com/imgml/TP/teams/logos/50x50/50149.png",
};

// ─── Next Fixture ──────────────────────────────────────────────────────────
export const NEXT_MATCH = {
  opponent: "Sunderland",
  shortName: "SUN",
  home: false,
  date: "2026-07-25T23:00:00",
  competition: "PSF",
  venue: "Geodis Park, Nashville",
  broadcast: "LFCTV GO",
};

// ─── Match Results (sourced from ESPN, BBC, PL) ────────────────────────────
// result: "W" | "D" | "L"
export const RESULTS = [
  { date: "2026-05-24", opponent: "Brentford",          home: true,  score: "1-1", competition: "PL", result: "D", scorers: "Jones 58'" },
  { date: "2026-05-15", opponent: "Aston Villa",        home: false, score: "2-4", competition: "PL", result: "L", scorers: "Van Dijk 52', 90+" },
  { date: "2026-05-09", opponent: "Chelsea",            home: true,  score: "1-1", competition: "PL", result: "D", scorers: "Gravenberch 6'" },
  { date: "2026-05-03", opponent: "Manchester United", home: false, score: "2-3", competition: "PL", result: "L", scorers: "Szoboszlai 47', Gakpo 56'" },
  { date: "2026-04-25", opponent: "Crystal Palace",home: true,  score: "3-1", competition: "PL",   result: "W", scorers: "Isak, Robertson, Wirtz 90+" },
  { date: "2026-04-19", opponent: "Everton",       home: false, score: "2-1", competition: "PL",   result: "W", scorers: "Salah, Van Dijk 90+10'" },
  { date: "2026-04-14", opponent: "PSG",           home: true,  score: "0-2", competition: "UCL",  result: "L", scorers: "" },
  { date: "2026-04-11", opponent: "Fulham",        home: true,  score: "2-0", competition: "PL",   result: "W", scorers: "Ngumoha, Salah" },
  { date: "2026-04-08", opponent: "PSG",          home: false, score: "0-2", competition: "UCL",  result: "L", scorers: "" },
  { date: "2026-04-04", opponent: "Man City",     home: false, score: "0-4", competition: "FA",   result: "L", scorers: "" },
  { date: "2026-03-21", opponent: "Brighton",     home: false, score: "1-2", competition: "PL",   result: "L", scorers: "Kerkez" },
  { date: "2026-03-18", opponent: "Galatasaray", home: true,  score: "4-0", competition: "UCL",  result: "W", scorers: "Szoboszlai, Ekitike, Gravenberch, Salah" },
  { date: "2026-03-15", opponent: "Tottenham",   home: true,  score: "1-1", competition: "PL",   result: "D", scorers: "Gakpo" },
  { date: "2026-03-10", opponent: "Galatasaray", home: false, score: "0-1", competition: "UCL",  result: "L", scorers: "" },
  { date: "2026-03-06", opponent: "Wolves",      home: false, score: "3-1", competition: "FA",   result: "W", scorers: "Ekitike 2, Wirtz" },
  { date: "2026-03-03", opponent: "Wolves",      home: false, score: "1-2", competition: "PL",   result: "L", scorers: "Szoboszlai" },
  { date: "2026-02-28", opponent: "West Ham",     home: true,  score: "5-2", competition: "PL",   result: "W", scorers: "Ekitike 2, Salah, Gakpo, Szoboszlai" },
  { date: "2026-02-22", opponent: "Nott'm Forest",home: false, score: "1-0", competition: "PL",   result: "W", scorers: "Mac Allister" },
  { date: "2026-02-14", opponent: "Brighton",     home: true,  score: "3-0", competition: "FA",   result: "W", scorers: "Ekitike 2, Gakpo" },
  { date: "2026-02-11", opponent: "Sunderland",   home: false, score: "1-0", competition: "PL",   result: "W", scorers: "Gravenberch" },
  { date: "2026-02-08", opponent: "Man City",     home: false, score: "1-2", competition: "PL",   result: "L", scorers: "Salah" },
  { date: "2026-01-31", opponent: "Newcastle",    home: true,  score: "4-1", competition: "PL",   result: "W", scorers: "Ekitike 2, Wirtz, Salah" },
  { date: "2026-01-24", opponent: "Bournemouth",  home: false, score: "2-3", competition: "PL",   result: "L", scorers: "Gakpo, Szoboszlai" },
  { date: "2026-01-17", opponent: "Burnley",      home: true,  score: "1-1", competition: "PL",   result: "D", scorers: "Van Dijk" },
  { date: "2026-01-12", opponent: "Barnsley",     home: true,  score: "4-1", competition: "FA",   result: "W", scorers: "Ngumoha, Gakpo, Jones, Wirtz" },
  { date: "2026-01-08", opponent: "Arsenal",      home: false, score: "0-0", competition: "PL",   result: "D", scorers: "" },
];

// ─── Premier League Standings (LIVE — sourced from ESPN site.api) ──────────
// Fetched daily by the liverpool-tracker-update skill from:
//   http://site.api.espn.com/apis/v2/sports/soccer/eng.1/standings
// `qualification` is derived from ESPN's note.description field:
//   "UCL" = Champions League, "UEL" = Europa League, "UECL" = Conference League,
//   "REL" = Relegation. Liverpool's row is flagged with `highlight: true`.
// Last refresh: 2026-06-06 — FINAL 20-team table re-verified against ESPN, 2025-26 season complete (MW38).
export const STANDINGS = [
  { pos: 1, team: "Arsenal", p: 38, w: 26, d: 7, l: 5, gd: 44, pts: 85, qualification: "UCL" },
  { pos: 2, team: "Manchester City", p: 38, w: 23, d: 9, l: 6, gd: 42, pts: 78, qualification: "UCL" },
  { pos: 3, team: "Manchester United", p: 38, w: 20, d: 11, l: 7, gd: 19, pts: 71, qualification: "UCL" },
  { pos: 4, team: "Aston Villa", p: 38, w: 19, d: 8, l: 11, gd: 7, pts: 65, qualification: "UCL" },
  { pos: 5, team: "Liverpool", p: 38, w: 17, d: 9, l: 12, gd: 10, pts: 60, qualification: "UCL", highlight: true },
  { pos: 6, team: "Bournemouth", p: 38, w: 13, d: 18, l: 7, gd: 4, pts: 57, qualification: "UEL" },
  { pos: 7, team: "Sunderland", p: 38, w: 14, d: 12, l: 12, gd: -6, pts: 54, qualification: "UEL" },
  { pos: 8, team: "Brighton", p: 38, w: 14, d: 11, l: 13, gd: 6, pts: 53, qualification: "UECL" },
  { pos: 9, team: "Brentford", p: 38, w: 14, d: 11, l: 13, gd: 3, pts: 53 },
  { pos: 10, team: "Chelsea", p: 38, w: 14, d: 10, l: 14, gd: 6, pts: 52 },
  { pos: 11, team: "Fulham", p: 38, w: 15, d: 7, l: 16, gd: -4, pts: 52 },
  { pos: 12, team: "Newcastle", p: 38, w: 14, d: 7, l: 17, gd: -2, pts: 49 },
  { pos: 13, team: "Everton", p: 38, w: 13, d: 10, l: 15, gd: -3, pts: 49 },
  { pos: 14, team: "Leeds", p: 38, w: 11, d: 14, l: 13, gd: -7, pts: 47 },
  { pos: 15, team: "Crystal Palace", p: 38, w: 11, d: 12, l: 15, gd: -10, pts: 45, qualification: "UEL" },
  { pos: 16, team: "Nott'm Forest", p: 38, w: 11, d: 11, l: 16, gd: -3, pts: 44 },
  { pos: 17, team: "Tottenham", p: 38, w: 10, d: 11, l: 17, gd: -9, pts: 41 },
  { pos: 18, team: "West Ham", p: 38, w: 10, d: 9, l: 19, gd: -19, pts: 39, qualification: "REL" },
  { pos: 19, team: "Burnley", p: 38, w: 4, d: 10, l: 24, gd: -37, pts: 22, qualification: "REL" },
  { pos: 20, team: "Wolves", p: 38, w: 3, d: 11, l: 24, gd: -41, pts: 20, qualification: "REL" },
];

// ─── Standings Commentary (refreshed alongside STANDINGS by the skill) ─────
// Hand-written by the skill on each daily run. `overview` is a 3-5 sentence
// paragraph that frames the table as a whole; `teams` is keyed by team name
// (matching STANDINGS[].team) and holds an optional one-line note per row.
// Only Liverpool + the most newsworthy rows need a note — empty teams render
// nothing beneath their row.
export const STANDINGS_COMMENTARY = {
  source: "ESPN",
  sourceUrl: "https://www.espn.com/soccer/table/_/league/eng.1",
  matchweek: 38,
  generatedAt: "2026-06-09T08:15:00Z",
  overview:
    "The table has been settled for a fortnight; the league it froze is now only a backdrop to the market churning in front of it. Arsenal are champions on 85, City, United and Villa fill the automatic Champions League berths, and Liverpool's fifth place on 60 reads as the budget line for a summer rebuild rather than a verdict on the season past. The week's energy is in the dealing: club-to-club talks for Yan Diomandé give the rebuild its first real attacking thrust, even as Inter press to take Curtis Jones and Konaté's free move to Madrid awaits only its photograph. Fifth bought a Champions League return without the points to enjoy it — twenty-five behind Arsenal, three clear of sixth-placed Bournemouth, the club whose manager and now whose midfielder Liverpool are raiding. Thirty-eight games decided where everyone sits; the ten weeks to August decide who is still in the seats.",
  teams: {
    "Arsenal": "Champions on 85 — the twenty-five-point gap to Liverpool's row is the number Iraola was hired to close.",
    "Manchester City": "Second on 78 — back in the winger market and still lurking on the Ordóñez file as Liverpool's defensive search turns urgent.",
    "Manchester United": "Third on 71 — back at the top table and among the clubs tipped to rival Liverpool for Bournemouth's Alex Scott.",
    "Aston Villa": "Fourth on 65 — the last automatic UCL berth, and the side Curtis Jones is said to be ready to snub for Inter.",
    "Liverpool": "Fifth on 60 — Champions League secured; the summer is the whole story now, Diomandé talks opening as Jones nears Inter and Konaté waits to be unveiled at Madrid.",
    "Bournemouth": "Sixth and into Europe — the club-best season keeps being taxed by Anfield: after Iraola and his staff, now a £40m move for Alex Scott.",
    "Sunderland": "Seventh and into Europe in their promotion season — Iraola's first assignment, Nashville, July 25.",
    "Brighton": "Eighth — a Conference League play-off place extends the European streak; van Hecke remains a quiet Liverpool defensive file.",
    "Brentford": "Ninth on 53 — level with Brighton but out of Europe for the first time in their top-flight era; hosts of the season's final-day 1-1 on May 24.",
    "Chelsea": "Tenth on 52 — a third straight year without the Champions League, and still monitoring Liverpool's £40m defensive target Ordóñez.",
    "Newcastle": "Twelfth on 49 — outside Europe after banking ~£70m for Anthony Gordon from Barcelona, and among those sounding out the available Gakpo.",
    "Crystal Palace": "Fifteenth on points, in Europe by silverware — their rejected £34.6m Ordóñez bid set the floor Liverpool's £40m offer must clear.",
    "Tottenham": "Survived in 17th — home already to Robertson on a free, and still strongly keen on the available Gakpo.",
    "West Ham": "Relegated in 18th — and a Liverpool shopping aisle: Summerville lingers on the wide-forward list as the fire sale nears.",
    "Burnley": "Relegated — 22 points and straight back down.",
    "Wolves": "Bottom on 20 — the season's worst side by every measure.",
  },
};

// ─── Dispatches (hand-curated long reads — separate from the wire feed) ────
export const DISPATCHES = [
  {
    n: "01",
    headline: "From Admiring To Negotiating.",
    byline: "Fabrizio Romano / TeamTalk",
    dateline: "Leipzig · 9 June",
    category: "Transfers",
    body: "For weeks the Diomandé story was a verb tense — Liverpool *were interested*, Liverpool *would like*. On Tuesday it became the present continuous: the 19-year-old has said yes, club-to-club talks with Leipzig are open, and both player and club want the thing settled before the World Cup begins on Thursday. David Ornstein has the Reds ahead of PSG on personal terms; what remains is the fee, Leipzig holding near €140m for a winger they would rather not sell at all, with even Cody Gakpo floated as a way to bridge it. A summer that had only known subtraction is, at last, trying to add — and trying to do it against a clock.",
  },
  {
    n: "02",
    headline: "The Man Who Scored That Goal Says Goodbye.",
    byline: "The Players' Tribune / ESPN",
    dateline: "Liverpool · 8 June",
    category: "Farewells",
    body: "Divock Origi never started enough games to be a great player, and somehow that was never the point. On Monday, at thirty-one, he retired — an open letter, a quiet exit, a line that read like a benediction: 'my purpose in the game as a player is fulfilled.' Forty-one goals in 175 appearances undersells him; what he leaves is a feeling, the corner against Barcelona, the toe-poke in Madrid, the way a stadium learned to expect the impossible whenever he was near it. He goes to study fashion. The folk hero of 2019 walks out just as the club that loved him learns to live without another generation of its legends.",
  },
  {
    n: "03",
    headline: "The Cleanest Exit Is The Homegrown One.",
    byline: "Liverpool.com / TheHardTackle",
    dateline: "Milan · 9 June",
    category: "Transfers",
    body: "Of all the names on Iraola's quiet clear-out, Curtis Jones is the one moving with the least drama and the most certainty. Inter have arranged a fresh meeting with Richard Hughes to push a deal toward the line near €25m, an opening €20m having been waved away. Jones, by the reporting, is prioritising San Siro and ready to turn down Aston Villa for it — a Scouser who came through the academy choosing Serie A over a stay in the Premier League. For the accountants it lands as near-pure profit; for the Kop it is one more thread of the title-winning weave pulled loose, sold not in anger but in arithmetic.",
  },
  {
    n: "04",
    headline: "He Knows Exactly Who He Wants.",
    byline: "Football365 / GiveMeSport",
    dateline: "AXA Training Centre · 8 June",
    category: "Manager",
    body: "A new manager's first signing is a sentence about himself, and Andoni Iraola keeps reaching for players he already trusts. The latest is Alex Scott, the 22-year-old he coached at Bournemouth, now floated as a possible £40m arrival and a candidate to be the opening name of his Anfield tenure. The valuation argues — Bournemouth want nearer £60m, and United and Tottenham are watching — but the logic is unmistakable. Having already taken Iraola and half his backroom staff from the south coast, Liverpool may now take his midfielder too, building the new era out of the parts the manager knows best.",
  },
  {
    n: "05",
    headline: "Nostalgia Knocks At The Door.",
    byline: "This Is Anfield / Rousing The Kop",
    dateline: "Anfield · 8 June",
    category: "Football News",
    body: "Every rebuild summons its ghosts, and this week one of Liverpool's louder ones came knocking. Reports from Spain say Darwin Núñez would welcome a return, possibly as a free agent should his Al-Hilal contract be torn up, with Barcelona also listening. He was maddening here — the misses a meme, the talent never in doubt — and a fanbase that argued about him for two years is being asked to argue again. With Ekitike lost to a ruptured Achilles and Gakpo asking to leave, the forward line has room. Whether FSG would fill it with a player they sold remains the question hanging over a thinning attack.",
  },
];

// ─── AI News Digest (generated via Claude + Perplexity) ─────────────────────
export const NEWS_DIGEST = {
  generatedAt: "2026-06-09T08:15:00Z",
  summary:
    "As of Tuesday June 9, the summer's first marquee arrival is suddenly in motion: club-to-club talks between Liverpool and RB Leipzig have opened for Yan Diomandé after the 19-year-old said yes to Anfield, and both player and club want it done before the World Cup kicks off on Thursday — though Leipzig's ~€140m valuation still has to be bridged. The exits move with it: Inter have lined up a fresh meeting to seal Curtis Jones near €25m, the midfielder said to be prioritising San Siro over Aston Villa. Off the pitch, an era closed quietly — Divock Origi, the 2019 Champions League folk hero, retired at 31 with an open letter — while Darwin Núñez is reported to want an Anfield return as a possible free agent. Beneath the fresh business the standing storylines hold: Konaté's free move to Real Madrid is sealed and awaiting its unveiling, Mac Allister is still pulled between the two Madrids, and Salah carries his goodbye into the World Cup as Egypt's captain.",
  keyTopics: [
    {
      title: "Diomandé Deal Accelerates — Club-To-Club Talks Open As Liverpool Race The World Cup Clock (TeamTalk / Fabrizio Romano / FootballFanCast, reported Mon Jun 8-Tue Jun 9)",
      detail:
        "The summer's defining attacking move shifted from rumour to negotiation overnight. With Yan Diomandé having said yes to Anfield, club-to-club talks with RB Leipzig are now open, and both the 19-year-old and Liverpool want the deal closed before the World Cup begins Thursday. David Ornstein places the Reds ahead of PSG on personal terms; the obstacle is the fee, Leipzig holding near €140m (~£120m) for a winger cast as the long-term heir to Salah's right flank. A summer measured by subtraction is suddenly chasing its first big addition.",
      category: "transfers",
    },
    {
      title: "Inter Line Up A Fresh Meeting To Seal Curtis Jones (Liverpool.com / TheHardTackle / Anfield Watch, reported Sun Jun 7-Tue Jun 9)",
      detail:
        "The clearest exit is now the academy graduate's. Inter Milan are reported to have arranged a fresh meeting with Richard Hughes to push a Curtis Jones deal toward the line at around €25m, after an opening €20m was rejected. Jones, reported to be prioritising San Siro and ready to snub Aston Villa, is among the names Iraola may move on, and the sale would register as near-pure profit on the books. With the window opening June 15, both sides are circling a number rather than a fundamental disagreement.",
      category: "transfers",
    },
    {
      title: "Divock Origi Retires At 31 — A Champions League Folk Hero Bows Out (ESPN / The Players' Tribune / This Is Anfield, reported Mon Jun 8)",
      detail:
        "On Monday the man who scored that goal against Barcelona said goodbye to football. Divock Origi, 31, announced his retirement in an open letter — 'my purpose in the game as a player is fulfilled' — closing a career that brought 41 goals in 175 Liverpool appearances, a Premier League, a Champions League and the two strikes in the 2019 semi-final and final that fixed him forever in Anfield folklore. He leaves to study fashion. For a club mid-rebuild, a reminder that the legends of one era keep stepping quietly out of the next.",
      category: "general",
    },
    {
      title: "Darwin Núñez 'Would Like' An Anfield Return — A Free-Agent Path Floated (This Is Anfield / Rousing The Kop / Liverpool.com, reported Sat Jun 6-Tue Jun 9)",
      detail:
        "A sentimental sub-plot stirred this week: reports from Spain say Darwin Núñez would welcome a Liverpool return, and could even arrive as a free agent should his Al-Hilal contract be terminated. Barcelona are said to be among the interested parties, and FSG's stance is the open question — a divisive former No. 9 floated back into a forward line that has just lost Ekitike to injury and may yet lose Gakpo. A long shot dressed in nostalgia, but a live one.",
      category: "transfers",
    },
    {
      title: "Alex Scott Emerges As A Possible 'First Iraola Signing' (Football365 / GiveMeSport / TeamTalk, reported Sun Jun 7-Mon Jun 8)",
      detail:
        "The opening arrival may have a name. Reports say Liverpool are weighing a £40m bid for Bournemouth's Alex Scott — a 22-year-old Iraola knows intimately from the south coast — as a candidate to be his first signing, with the manager 'pushing' a reunion. The snag is familiar: Bournemouth value the midfielder nearer £60m, and Manchester United and Tottenham are keeping tabs. Another Cherries raid after Iraola and his staff, it would add legs to a midfield bracing for Jones's and possibly Mac Allister's exits.",
      category: "transfers",
    },
    {
      title: "Gakpo Floated As Diomandé Leverage After His Transfer Request (TeamTalk / Liverpool.com / GiveMeSport, reported Fri Jun 6-Tue Jun 9)",
      detail:
        "The Gakpo situation took a tactical turn. Having handed in a transfer request — unwilling to fight Rio Ngumoha for the left wing under Iraola — the Dutch forward is now reported as possible makeweight in a swap to bring Diomandé from Leipzig, with Tottenham still strongly interested in a straight sale near €45m. Whether as cash or as leverage, a nine-goal forward who flowered under Slot is being priced into the very deal that would replace him.",
      category: "transfers",
    },
    {
      title: "Konaté's Real Madrid Free Transfer Sealed, Awaiting Its Unveiling (Managing Madrid / This Is Anfield / Real Madrid, reported Sun Jun 7-Mon Jun 8)",
      detail:
        "The biggest departure is now a formality awaiting a photograph. Florentino Pérez's re-election at the Bernabéu cleared the last condition on Ibrahima Konaté's four-year free transfer to Real Madrid (~€24m gross a season), with the announcement freed to follow within days. A France international leaves for nothing — the cost of a stalled extension — and the right-sided centre-back vacancy the £40m Ordóñez bid is built to fill is now permanent.",
      category: "transfers",
    },
    {
      title: "Mac Allister Still Pulled Between The Two Madrids (Anfield Watch / Sportingpedia / This Is Anfield, reported Wed Jun 3-Mon Jun 8)",
      detail:
        "The midfield question has not eased. Both Real Madrid and Atlético remain linked with Alexis Mac Allister, the 27-year-old into the final two years of a deal with no extension talks underway — pointed against Gravenberch's fresh signature. His father Carlos again denied a formal approach while conceding his son views La Liga warmly. Flagged internally as sellable near €120m, the World Cup winner is the sell-to-buy fuel a midfield reshape would run on.",
      category: "transfers",
    },
    {
      title: "Salah Carries His Goodbye Into The World Cup As Egypt's Captain (Al Jazeera / beIN Sports / The National, reported Sat Jun 6-Mon Jun 8)",
      detail:
        "The farewell detours through North America. Mohamed Salah, his Liverpool contract lapsing June 30, leads Egypt into the tournament as captain and will not settle his club future until it is over. The market has reordered around the wait — Turkey now ahead of Saudi Arabia and MLS, a sentimental Italian return floated third. Nine years, a city's affection, one more summer in green before the last line is written.",
      category: "general",
    },
    {
      title: "Ordóñez Holds As The Defensive Priority, Chelsea And City Watching (Sky Sports / Football365 / TeamTalk, reported Wed Jun 3-Mon Jun 8)",
      detail:
        "With Konaté's exit settled, the right-sided centre-back search is the file Liverpool most need to close. Club Brugge's 22-year-old Joël Ordóñez stays the name they are furthest down on — a ~£40m offer pitched as half of an 'approved' double that could reach £170m alongside a winger — with Chelsea and Manchester City monitoring and a rejected £34.6m Palace bid setting the floor. Jacquet, recovering from a shoulder operation, is the in-house cover until it lands.",
      category: "transfers",
    },
  ],
  sources: [
    "TeamTalk",
    "Fabrizio Romano",
    "FootballFanCast",
    "David Ornstein",
    "ESPN",
    "The Players' Tribune",
    "This Is Anfield",
    "Liverpool.com",
    "TheHardTackle",
    "Anfield Watch",
    "Rousing The Kop",
    "Football365",
    "GiveMeSport",
    "Managing Madrid",
    "Real Madrid",
    "Sky Sports",
    "Al Jazeera",
    "beIN Sports",
    "The National",
  ],
};

// ─── Transfer Targets (2026 summer window) ─────────────────────────────────
// Hand-curated; refresh via Perplexity the same way NEWS_DIGEST is refreshed.
// heatTier: "hot" (≥65%) | "warm" (40-64%) | "cool" (<40%) | "done" | "dead"
// sources[].tier: "S" (Romano-class) | "A" (major outlet) | "B" (beat) | "C" (aggregator)
export const TRANSFER_TARGETS = {
  generatedAt: "2026-06-09T08:15:00Z",
  summary:
    "Tuesday's ledger opens on movement, not just rumour: club-to-club talks between Liverpool and RB Leipzig are now open for Yan Diomandé after the 19-year-old said yes to Anfield, with both sides pushing to close before the World Cup begins Thursday — though Leipzig's ~€140m valuation is the gap still to bridge, and a Gakpo-as-makeweight swap has been floated. The exits move in step: Inter have lined up a fresh meeting to seal Curtis Jones near €25m, and a new attacking name has surfaced — a possible £40m bid for Bournemouth's Alex Scott, the reunion Iraola is said to be 'pushing,' against the Cherries' £60m ask. The standing files hold beneath the fresh business: Konaté's free move to Real Madrid is sealed and awaiting unveiling, leaving Club Brugge's Ordóñez the priority defensive target at ~£40m; Mac Allister stays pulled between the two Madrids; Salah carries his decision into the tournament; and Ngumoha remains untouchable as Alisson digs in to stay.",
  incoming: [
    {
      id: "varela-2026",
      name: "Alan Varela",
      age: 24,
      position: "MID",
      role: "Deep-lying midfielder (No. 6)",
      nationality: "🇦🇷 Argentina",
      foot: "Right",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/FC%20Salzburg%20gegen%20FC%20Porto%20(2025-09-25%20UEFA%20Euro%20League%20)%2063.jpg?width=400",
      currentClub: "Porto",
      currentLeague: "Primeira Liga",
      feeMin: 60, feeMax: 75, feeCurrency: "€m",
      marketValue: 50,
      wageBand: "B",
      contractExpiry: "2028-06-30",
      releaseClause: "€75m",
      contractNote: "André Villas-Boas inserted a €75m release clause; talks could bring the price down.",
      probability: 40,
      heatTier: "warm",
      sources: [
        { name: "Anfield Watch",  tier: "B" },
        { name: "Liverpool.com",  tier: "B" },
        { name: "Caught Offside", tier: "C" },
      ],
      lastUpdated: "2026-06-03",
      rumorNote:
        "Wed 3 Jun — coy, but still near the front of the queue. Asked by La Nación about the Liverpool links, Varela said only that he is 'calm and 100% focused here in Porto' and leaving his future to his agent. The 24-year-old Argentine title-winner, a Boca Juniors product drawing Mascherano comparisons for his ball-recovery and crisp vertical passing, carries a €75m clause and remains the on-the-ball No. 6 the side has lacked — though United, who see a Casemiro heir, and City, eyeing a Rodri successor, are in the same race, and Liverpool may wait for Iraola to make the call.",
      positionFit: {
        replaces: "Endo (defensive midfield)",
        competesWith: ["Gravenberch", "Mac Allister"],
        depthAfter: "Gravenberch · Varela · Mac Allister",
      },
      stats: {
        apps: 41, goals: 2, assists: 3,
        tacklesPer90: 2.6, passCompletion: 89, progressiveCarries: 2.4,
        cleanSheets: 0, xG: 0.9,
      },
    },
    {
      id: "wharton-2026",
      name: "Adam Wharton",
      age: 22,
      position: "MID",
      role: "Deep-lying midfielder (No. 6)",
      nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England",
      foot: "Right",
      image: "https://resources.premierleague.com/premierleague/photos/players/250x250/p496221.png",
      currentClub: "Crystal Palace",
      currentLeague: "Premier League",
      feeMin: 70, feeMax: 90, feeCurrency: "£m",
      marketValue: 70,
      wageBand: "B",
      contractExpiry: "2029-06-30",
      releaseClause: null,
      contractNote: "Palace, fresh from a Conference League win, intend to offer a new contract rather than sell.",
      probability: 22,
      heatTier: "cool",
      sources: [
        { name: "TeamTalk",        tier: "B" },
        { name: "This Is Anfield",  tier: "A" },
        { name: "Rousing The Kop",  tier: "C" },
      ],
      lastUpdated: "2026-06-02",
      rumorNote:
        "Tue 2 Jun — still on Iraola's list, but no longer at the front of it. Wharton remains named among the five signings the new manager has requested, yet Palace — buoyed by a Conference League triumph — are minded to offer a new deal rather than sell, and Liverpool's energy has shifted to Porto's Alan Varela. The £80m England man stays the romantic option for the base of midfield; the realistic one now wears Porto blue.",
      positionFit: {
        replaces: "Endo (defensive midfield)",
        competesWith: ["Gravenberch", "Mac Allister"],
        depthAfter: "Gravenberch · Wharton · Mac Allister",
      },
      stats: {
        apps: 32, goals: 1, assists: 4,
        tacklesPer90: 2.3, passCompletion: 88, progressiveCarries: 3.1,
        cleanSheets: 0, xG: 0.8,
      },
    },
    {
      id: "scott-2026",
      name: "Alex Scott",
      age: 22,
      position: "MID",
      role: "Box-to-box midfielder",
      nationality: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England",
      foot: "Right",
      image: "https://resources.premierleague.com/premierleague/photos/players/250x250/p465490.png",
      currentClub: "Bournemouth",
      currentLeague: "Premier League",
      feeMin: 40, feeMax: 60, feeCurrency: "£m",
      marketValue: 45,
      wageBand: "C",
      contractExpiry: "2029-06-30",
      releaseClause: null,
      contractNote: "Bournemouth value him near £60m; Liverpool's interest is pitched around £40m.",
      probability: 38,
      heatTier: "warm",
      sources: [
        { name: "Football365",  tier: "B" },
        { name: "GiveMeSport",  tier: "B" },
        { name: "TeamTalk",     tier: "B" },
      ],
      lastUpdated: "2026-06-09",
      rumorNote:
        "Bournemouth · 9 Jun — a reunion the manager is said to be pushing. Reports place Liverpool weighing a ~£40m bid for the 22-year-old Iraola coached on the south coast, floated as a candidate to be the new head coach's first signing. The gap is the valuation — Bournemouth want closer to £60m — and the competition is real, with Manchester United and Tottenham keeping tabs. Another Cherries raid after Iraola and his backroom staff, it would add legs to a midfield bracing for Jones's, and perhaps Mac Allister's, departure.",
      positionFit: {
        replaces: "Jones / Endo (midfield depth)",
        competesWith: ["Gravenberch", "Szoboszlai"],
        depthAfter: "Gravenberch · Scott · Szoboszlai",
      },
      stats: {
        apps: 37, goals: 4, assists: 6,
        tacklesPer90: 2.2, passCompletion: 85, progressiveCarries: 3.4,
        cleanSheets: 0, xG: 3.1,
      },
    },
    {
      id: "diomande-2026",
      name: "Yan Diomandé",
      age: 19,
      position: "FWD",
      role: "Right winger",
      nationality: "🇨🇮 Ivory Coast",
      foot: "Two-footed",
      image: "https://assets.bundesliga.com/contender/2025/11/2526_MD10_TSGRBL_SW_151.jpg?crop=338px,0px,1352px,1080px&fit=540,540",
      currentClub: "RB Leipzig",
      currentLeague: "Bundesliga",
      feeMin: 110, feeMax: 140, feeCurrency: "£m",
      marketValue: 75,
      wageBand: "C",
      contractExpiry: "2030-06-30",
      releaseClause: null,
      contractNote: "Contract to 2030, no release clause; Leipzig holding near €140m (~£120m) as the asking price.",
      probability: 58,
      heatTier: "warm",
      sources: [
        { name: "Fabrizio Romano", tier: "S" },
        { name: "TeamTalk",        tier: "B" },
        { name: "FootballFanCast", tier: "C" },
      ],
      lastUpdated: "2026-06-09",
      rumorNote:
        "Leipzig · 9 Jun — talks are live. With the 19-year-old having said yes to Anfield, club-to-club negotiations with Leipzig are now open, and both player and club want the move done before the World Cup begins Thursday. David Ornstein places Liverpool ahead of PSG on personal terms; the gap is purely the fee, Leipzig holding near €140m (~£120m) for a winger they are reluctant to sell at all. Reports even float Cody Gakpo as a possible makeweight to bridge it. Sporting's Trincão remains the cheaper fallback, but for the first time this summer the Reds are negotiating, not just admiring.",
      positionFit: {
        replaces: "Salah (right wing)",
        competesWith: ["Gakpo", "Ngumoha"],
        depthAfter: "Diomandé · Gakpo · Ngumoha",
      },
      stats: {
        apps: 31, goals: 13, assists: 10,
        tacklesPer90: 0.8, passCompletion: 78, progressiveCarries: 5.4,
        cleanSheets: 0, xG: 11.2,
      },
    },
    {
      id: "trincao-2026",
      name: "Francisco Trincão",
      age: 26,
      position: "FWD",
      role: "Right winger / inside forward",
      nationality: "🇵🇹 Portugal",
      foot: "Left",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Francisco_Trinc%C3%A3o_USMNT_v_Portugal_Mar_31_2026-55_%28cropped%29.jpg/500px-Francisco_Trinc%C3%A3o_USMNT_v_Portugal_Mar_31_2026-55_%28cropped%29.jpg",
      currentClub: "Sporting CP",
      currentLeague: "Primeira Liga",
      feeMin: 55, feeMax: 65, feeCurrency: "€m",
      marketValue: 45,
      wageBand: "B",
      contractExpiry: "2028-06-30",
      releaseClause: "€60m",
      contractNote: "Carries a ~€60m release clause; Sporting won't open talks until after the World Cup.",
      probability: 52,
      heatTier: "warm",
      sources: [
        { name: "Empire of the Kop", tier: "B" },
        { name: "Football365",   tier: "B" },
        { name: "Record (PT)",   tier: "B" },
      ],
      lastUpdated: "2026-06-08",
      rumorNote:
        "Lisbon · 8 Jun — still 'at the very top of the shortlist,' even as Diomandé warms. Iraola's preference for a wide forward who can start now keeps the Sporting man the steady alternative, and the maths keep arguing for him: a ~€60m clause against the ~€100m Leipzig want, a Premier-League-proven 26-year-old rather than a teenage project. The one fixed obstacle is the calendar — Sporting won't open talks until after the World Cup, where Trincão is likely to feature for Portugal — so any move here is a July or August deal, not a June one.",
      positionFit: {
        replaces: "Salah (right wing)",
        competesWith: ["Gakpo", "Ngumoha"],
        depthAfter: "Trincão · Gakpo · Ngumoha",
      },
      stats: {
        apps: 47, goals: 16, assists: 11,
        tacklesPer90: 1.0, passCompletion: 81, progressiveCarries: 4.3,
        cleanSheets: 0, xG: 12.7,
      },
    },
    {
      id: "rayan-2026",
      name: "Rayan",
      age: 19,
      position: "FWD",
      role: "Winger",
      nationality: "🇧🇷 Brazil",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rayan_2026.png/500px-Rayan_2026.png",
      currentClub: "Bournemouth",
      currentLeague: "Premier League",
      feeMin: 100, feeMax: 130, feeCurrency: "£m",
      marketValue: 65,
      wageBand: "C",
      contractExpiry: "2031-06-30",
      releaseClause: "£130m (Jan window only)",
      contractNote: "Release clause activates only in January and lowers thereafter; expected to stay until at least Jan 2027.",
      probability: 15,
      heatTier: "cool",
      sources: [
        { name: "This Is Anfield", tier: "A" },
        { name: "TeamTalk",        tier: "B" },
        { name: "Football365",     tier: "B" },
      ],
      lastUpdated: "2026-06-06",
      rumorNote:
        "Bournemouth · 6 Jun — a name for the medium term. Iraola knows the 19-year-old Brazil winger intimately — he managed him on the south coast after January's move from Vasco da Gama — and is reported a 'huge fan,' with Rayan named among his 'first three targets' and floated as a Salah heir. The structure says wait: a £130m release clause that only opens in January, lowering thereafter, means the realistic window is January 2027 at the earliest. A flag planted, not a deal pursued.",
      positionFit: {
        replaces: "Salah (long-term)",
        competesWith: ["Gakpo", "Ngumoha"],
        depthAfter: "Future: Rayan · Gakpo · Ngumoha",
      },
      stats: {
        apps: 15, goals: 5, assists: 2,
        tacklesPer90: 0.7, passCompletion: 79, progressiveCarries: 5.1,
        cleanSheets: 0, xG: 4.2,
      },
    },
    {
      id: "ordonez-2026",
      name: "Joël Ordóñez",
      age: 21,
      position: "DEF",
      role: "Centre-back (right-sided)",
      nationality: "🇪🇨 Ecuador",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/1/19/JoelOrd%C3%B3%C3%B1ez.jpg",
      currentClub: "Club Brugge",
      currentLeague: "Belgian Pro League",
      feeMin: 35, feeMax: 43, feeCurrency: "£m",
      marketValue: 32,
      wageBand: "C",
      contractExpiry: "2028-06-30",
      releaseClause: null,
      contractNote: "105 Brugge appearances at 21; Palace had a £34.6m bid rejected, setting the floor.",
      probability: 50,
      heatTier: "warm",
      sources: [
        { name: "Sky Sports",      tier: "A" },
        { name: "TeamTalk",        tier: "B" },
        { name: "CrunchSports",    tier: "C" },
      ],
      lastUpdated: "2026-06-08",
      rumorNote:
        "Bruges · 8 Jun — the priority file now Konaté's exit is sealed. With Pérez's re-election confirming the France international's free move to Madrid, the right-sided centre-back slot is permanently open and Ordóñez is the name Liverpool are furthest down on — a ~£40m bid pitched as one half of an 'approved' £170m double alongside a winger. The competition is real: Chelsea and Manchester City both monitor the 22-year-old Ecuadorian, and a rejected £34.6m Palace bid sets the floor. This is the deal the rebuild most needs to close, and the one Liverpool still lead.",
      positionFit: {
        replaces: "Konaté (right centre-back)",
        competesWith: ["Van Dijk", "Jacquet"],
        depthAfter: "Van Dijk · Ordóñez · Jacquet",
      },
      stats: {
        apps: 36, goals: 2, assists: 1,
        tacklesPer90: 2.1, passCompletion: 89, progressiveCarries: 1.3,
        cleanSheets: 14, xG: 1.1,
      },
    },
    {
      id: "kroupi-2026",
      name: "Eli Junior Kroupi",
      age: 19,
      position: "FWD",
      role: "Striker / second forward",
      nationality: "🇫🇷 France",
      foot: "Left",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Eli_Junior_Kroupi.jpg/500px-Eli_Junior_Kroupi.jpg",
      currentClub: "Bournemouth",
      currentLeague: "Premier League",
      feeMin: 80, feeMax: 100, feeCurrency: "£m",
      marketValue: 55,
      wageBand: "C",
      contractExpiry: "2029-06-30",
      releaseClause: null,
      contractNote: "Bournemouth's £80m-£100m valuation is set as a deterrent; they intend to keep him.",
      probability: 20,
      heatTier: "cool",
      sources: [
        { name: "Liverpool.com",    tier: "B" },
        { name: "FootballFanCast",  tier: "C" },
        { name: "Fabrizio Romano",  tier: "S" },
      ],
      lastUpdated: "2026-06-05",
      rumorNote:
        "Bournemouth · 5 Jun — the wall has gone up. The Cherries are now described as flatly determined to keep their 13-goal teenager, having already watched Iraola, Elphick, Cooper and de la Torre pack for Merseyside — the £80m-£100m valuation reads as a refusal dressed in numbers. The reunion logic survives (no manager knows the player better), but this file cools while the Diomandé money is committed elsewhere; a January re-opening looks likelier than a June one.",
      positionFit: {
        replaces: "Ekitike (during 9-12 month rehab)",
        competesWith: ["Isak", "Gakpo"],
        depthAfter: "Isak · Kroupi · Gakpo",
      },
      stats: {
        apps: 33, goals: 13, assists: 4,
        tacklesPer90: 0.6, passCompletion: 79, progressiveCarries: 2.9,
        cleanSheets: 0, xG: 11.8,
      },
    },
    {
      id: "lacroix-2026",
      name: "Maxence Lacroix",
      age: 26,
      position: "DEF",
      role: "Centre-back",
      nationality: "🇫🇷 France",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Lens_-_Sochaux_%2823-11-2019%29_73.jpg/330px-Lens_-_Sochaux_%2823-11-2019%29_73.jpg",
      currentClub: "Crystal Palace",
      currentLeague: "Premier League",
      feeMin: 40, feeMax: 55, feeCurrency: "€m",
      marketValue: 45,
      wageBand: "B",
      contractExpiry: "2028-06-30",
      releaseClause: null,
      contractNote: "Settled in the Premier League since 2024; Palace would demand a premium.",
      probability: 32,
      heatTier: "warm",
      sources: [
        { name: "TeamTalk",        tier: "B" },
        { name: "Liverpool World", tier: "C" },
        { name: "Goal",            tier: "B" },
      ],
      lastUpdated: "2026-06-08",
      rumorNote:
        "Mon 8 Jun — the queue in front of him has re-ordered: with Konaté's exit now sealed — his Madrid free transfer confirmed by Pérez's re-election — the right centre-back slot is formally open, but Football365's reporting puts Club Brugge's Ordóñez at the head of an 'approved' double rather than Lacroix. A Jarell Quansah buy-back — the ~€80m clause on the Leverkusen man drops next summer — Koulierakis and Schlotterbeck round out the list. Lacroix stays a live, Premier-League-proven name entering his peak, but the momentum this week is Belgian.",
      positionFit: {
        replaces: "Konaté (right centre-back)",
        competesWith: ["Van Dijk", "Jacquet"],
        depthAfter: "Van Dijk · Lacroix · Jacquet",
      },
      stats: {
        apps: 33, goals: 3, assists: 1,
        tacklesPer90: 1.9, passCompletion: 86, progressiveCarries: 1.1,
        cleanSheets: 9, xG: 1.4,
      },
    },
    {
      id: "vanhecke-2026",
      name: "Jan Paul van Hecke",
      age: 25,
      position: "DEF",
      role: "Centre-back",
      nationality: "🇳🇱 Netherlands",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Jan_Paul_van_Hecke_24012026_%282%29_%28cropped%29.jpg/330px-Jan_Paul_van_Hecke_24012026_%282%29_%28cropped%29.jpg",
      currentClub: "Brighton",
      currentLeague: "Premier League",
      feeMin: 35, feeMax: 50, feeCurrency: "€m",
      marketValue: 40,
      wageBand: "B",
      contractExpiry: "2027-06-30",
      releaseClause: null,
      contractNote: "Reportedly refusing a new deal with 18 months left — leverage for any suitor.",
      probability: 26,
      heatTier: "cool",
      sources: [
        { name: "TeamTalk",     tier: "B" },
        { name: "Sky Sports",   tier: "A" },
      ],
      lastUpdated: "2026-05-31",
      rumorNote:
        "Sun 31 May — remains the value alternative to Lacroix as the back line thins. One of the most-improved defenders in the Premier League, comfortable building from the back, with eighteen months left on a deal he is in no rush to extend — exactly the contractual softness Liverpool look for. Brighton drive a hard bargain, but each month that passes shifts the leverage.",
      positionFit: {
        replaces: "Konaté (centre-back depth)",
        competesWith: ["Van Dijk", "Lacroix", "Jacquet"],
        depthAfter: "Van Dijk · Lacroix / van Hecke · Jacquet",
      },
      stats: {
        apps: 30, goals: 1, assists: 1,
        tacklesPer90: 1.6, passCompletion: 88, progressiveCarries: 1.3,
        cleanSheets: 8, xG: 0.5,
      },
    },
    {
      id: "barcola-2026",
      name: "Bradley Barcola",
      age: 23,
      position: "FWD",
      role: "Winger",
      nationality: "🇫🇷 France",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Barcola_asse_psg_2425.png/330px-Barcola_asse_psg_2425.png",
      currentClub: "PSG",
      currentLeague: "Ligue 1",
      feeMin: 70, feeMax: 85, feeCurrency: "€m",
      marketValue: 75,
      wageBand: "B",
      contractExpiry: "2028-06-30",
      releaseClause: null,
      contractNote: "Out of favour under Luis Enrique; a name on the wide-forward longlist rather than an active pursuit.",
      probability: 22,
      heatTier: "cool",
      sources: [
        { name: "This Is Anfield",    tier: "A" },
        { name: "Football Transfers", tier: "B" },
        { name: "Liverpool.com",      tier: "B" },
      ],
      lastUpdated: "2026-06-08",
      rumorNote:
        "Paris · 8 Jun — a name kept on file, not chased. Even with the Diomandé pursuit warming again and Sporting's Trincão the clearer alternative, Barcola reads as a deeper contingency than an active target. The logic that once tied him to Anfield survives only loosely: a crowded Enrique front line could yet make the 23-year-old available, but nothing in this week's reporting puts Liverpool in the room. Warm only in the sense that a long list is always warm.",
      positionFit: {
        replaces: "Salah (alternative)",
        competesWith: ["Gakpo", "Ngumoha"],
        depthAfter: "Deeper option: Barcola · Gakpo · Ngumoha",
      },
      stats: {
        apps: 38, goals: 12, assists: 11,
        tacklesPer90: 0.7, passCompletion: 82, progressiveCarries: 5.0,
        cleanSheets: 0, xG: 10.4,
      },
    },
    {
      id: "summerville-2026",
      name: "Crysencio Summerville",
      age: 24,
      position: "FWD",
      role: "Left winger",
      nationality: "🇳🇱 Netherlands",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Crysencio_Summerville_of_West_Ham_United.jpeg/330px-Crysencio_Summerville_of_West_Ham_United.jpeg",
      currentClub: "West Ham",
      currentLeague: "Championship (relegated)",
      feeMin: 25, feeMax: 35, feeCurrency: "£m",
      marketValue: 30,
      wageBand: "C",
      contractExpiry: "2029-06-30",
      releaseClause: null,
      contractNote: "Relegation with West Ham opens the exit; no formal clause, but the club must sell to rebuild.",
      probability: 18,
      heatTier: "cool",
      sources: [
        { name: "Liverpool.com", tier: "B" },
      ],
      lastUpdated: "2026-06-05",
      rumorNote:
        "London · 5 Jun — a new line on the wide-forward list: the former Leeds dribbler, relegated with West Ham, is being floated as the value play in the Iraola rebuild — a left-sided one-v-one specialist who fits the manager's transition game at a fraction of the Diomandé toll. Early-stage interest from a single outlet for now; the file warms or dies when the window opens June 15 and West Ham's fire sale begins.",
      positionFit: {
        replaces: "Wide depth (left)",
        competesWith: ["Gakpo", "Ngumoha", "Chiesa"],
        depthAfter: "Gakpo · Summerville · Ngumoha",
      },
      stats: {
        apps: 34, goals: 7, assists: 6,
        tacklesPer90: 1.1, passCompletion: 80, progressiveCarries: 4.6,
        cleanSheets: 0, xG: 6.3,
      },
    },
    {
      id: "jacquet-2026",
      name: "Jérémy Jacquet",
      age: 20,
      position: "DEF",
      role: "Centre-back",
      nationality: "🇫🇷 France",
      foot: "Right",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Jacquet_asse_srfc_2425.png/330px-Jacquet_asse_srfc_2425.png",
      currentClub: "Rennes (loan)",
      currentLeague: "Ligue 1",
      feeMin: 63, feeMax: 70, feeCurrency: "€m",
      marketValue: 35,
      wageBand: "C",
      contractExpiry: "2030-06-30",
      releaseClause: null,
      contractNote: "Signed January 2026; loaned back to Rennes through the spring.",
      probability: 100,
      heatTier: "done",
      sources: [
        { name: "L'Équipe",       tier: "A" },
        { name: "So Foot",         tier: "A" },
        { name: "This Is Anfield", tier: "B" },
      ],
      lastUpdated: "2026-02-15",
      rumorNote:
        "Done — sold by Rennes to Liverpool in the winter window for a club-record €63m (rising to €70m with add-ons) and loaned straight back through May. A February shoulder dislocation ended the loan early; surgery followed. He arrives at Anfield this summer as the 2026-27 centre-back depth signing, twenty years old, the only confirmed name on the incoming sheet.",
      positionFit: {
        replaces: "Quansah (deferred to 2027)",
        competesWith: ["Konaté", "Van Dijk"],
        depthAfter: "Van Dijk · Konaté · Jacquet · academy",
      },
      stats: {
        apps: 22, goals: 0, assists: 1,
        tacklesPer90: 1.6, passCompletion: 85, progressiveCarries: 0.7,
        cleanSheets: 6, xG: 0.2,
      },
    },
  ],
  outgoing: [
    {
      id: "konate-out",
      name: "Ibrahima Konaté",
      position: "DEF",
      destination: "Real Madrid (free)",
      feeAsk: { min: 0, max: 0, currency: "€" },
      probability: 100,
      heatTier: "done",
      sources: [{ name: "Managing Madrid", tier: "A" }, { name: "Real Madrid", tier: "A" }, { name: "This Is Anfield", tier: "A" }],
      note: "Mon 8 Jun — sealed by a vote. Florentino Pérez's re-election at the Bernabéu on Sunday — a near two-thirds win, a mandate to 2030 — cleared the last condition on the four-year free transfer to Real Madrid, reported near €24m gross a season to 2030. Pérez had written the centre-back into his manifesto; with the presidency held, the formal unveiling is freed to follow within days. A France international walks for nothing, the bill for a stalled extension — and the vacancy at Anfield is the one the £40m Ordóñez bid is built to fill.",
    },
    {
      id: "robertson-out",
      name: "Andy Robertson",
      position: "DEF",
      destination: "Tottenham (free)",
      feeAsk: { min: 0, max: 0, currency: "€" },
      probability: 100,
      heatTier: "done",
      sources: [{ name: "Sky Sports", tier: "A" }, { name: "Tottenham Hotspur", tier: "A" }, { name: "Premier League", tier: "A" }],
      note: "Fri 5 Jun — confirmed and announced. Tottenham have signed the 32-year-old on a free, effective once his Liverpool deal lapses on June 30. Nine years and nine major trophies close as the title-winning core thins; the Kop's farewell came after the Brentford finale, and the left-back job passes formally to £45m Milos Kerkez.",
    },
    {
      id: "jones-out",
      name: "Curtis Jones",
      position: "MID",
      destination: "Inter Milan",
      feeAsk: { min: 22, max: 30, currency: "€m" },
      probability: 66,
      heatTier: "warm",
      sources: [{ name: "Liverpool.com", tier: "B" }, { name: "TheHardTackle", tier: "C" }, { name: "Anfield Watch", tier: "B" }],
      note: "Tue 9 Jun — the talks intensify: Inter have lined up a fresh meeting with Richard Hughes to push the deal toward the line near €25m, after their €20m opener was rejected. Jones is reported to be prioritising San Siro and ready to snub Aston Villa; with the window opening June 15, the two clubs are now circling a number rather than a disagreement. A homegrown sale that books as near-pure profit, and one of the cleaner exits of the reset.",
    },
    {
      id: "gakpo-out",
      name: "Cody Gakpo",
      position: "FWD",
      destination: "Tottenham / Leipzig swap (mooted)",
      feeAsk: { min: 45, max: 60, currency: "€m" },
      probability: 58,
      heatTier: "warm",
      sources: [{ name: "TeamTalk", tier: "B" }, { name: "Liverpool.com", tier: "B" }, { name: "GiveMeSport", tier: "B" }],
      note: "Tue 9 Jun — the request now has a strategic use: having asked to leave rather than fight Rio Ngumoha for the left wing under Iraola, Gakpo is reported as a possible makeweight in a swap to bring Diomandé from Leipzig, even as Tottenham stay strongly keen on a straight sale near €45m. Whether as cash or as leverage, a nine-goal forward who flowered under Slot is being priced into the very deal built to replace him.",
    },
    {
      id: "macallister-out",
      name: "Alexis Mac Allister",
      position: "MID",
      destination: "Real Madrid / Atlético (mooted)",
      feeAsk: { min: 90, max: 120, currency: "€m" },
      probability: 48,
      heatTier: "warm",
      sources: [{ name: "Sportingpedia", tier: "B" }, { name: "Anfield Watch", tier: "B" }, { name: "This Is Anfield", tier: "A" }],
      note: "Mon 8 Jun — the Madrid tug sharpens: both Real Madrid and Atlético are now reported to be eyeing the 27-year-old, who has no new-contract talks underway as he enters the last two years of his deal — pointed against Gravenberch's fresh extension. His father and agent Carlos again denied any formal approach while conceding the player views La Liga warmly. Already flagged internally as sellable, he is the sell-to-buy fuel Iraola's midfield reshape needs.",
    },
    {
      id: "salah-out",
      name: "Mohamed Salah",
      position: "FWD",
      destination: "Departure announced — decision after World Cup",
      feeAsk: { min: 0, max: 0, currency: "€" },
      probability: 75,
      heatTier: "warm",
      sources: [{ name: "This Is Anfield", tier: "A" }, { name: "ESPN", tier: "A" }, { name: "GiveMeSport", tier: "B" }],
      note: "Mon 8 Jun — the goodbye detours through the tournament: named Egypt captain for the 2026 World Cup, the forward will not decide his club future until it is done. The contract lapses June 30; the market has reordered around the wait, with Turkey now ahead of Saudi Arabia and MLS and a sentimental Italian return floated third. A nine-year story keeps its final line in pencil while its author plays one more summer in green.",
    },
    {
      id: "gomez-out",
      name: "Joe Gomez",
      position: "DEF",
      destination: "Serie A (Milan / Roma)",
      feeAsk: { min: 18, max: 22, currency: "€m" },
      probability: 62,
      heatTier: "warm",
      sources: [{ name: "Liverpool.com", tier: "B" }, { name: "Sports Mole", tier: "C" }],
      note: "Twelve months left; among the four further exits flagged in Iraola's squad reset.",
    },
    {
      id: "chiesa-out",
      name: "Federico Chiesa",
      position: "FWD",
      destination: "Italy (Napoli / Roma)",
      feeAsk: { min: 10, max: 15, currency: "€m" },
      probability: 70,
      heatTier: "hot",
      sources: [{ name: "Football Italia", tier: "A" }, { name: "DaveOCKOP", tier: "C" }],
      note: "A single-season recoup; the squad spot funds the rebuild.",
    },
    {
      id: "endo-out",
      name: "Wataru Endo",
      position: "MID",
      destination: "Bundesliga / Saudi",
      feeAsk: { min: 8, max: 12, currency: "€m" },
      probability: 58,
      heatTier: "warm",
      sources: [{ name: "Sky Sports", tier: "A" }],
      note: "Squad role reduced post-Mac Allister; modest fee, big wage save.",
    },
    {
      id: "tsimikas-out",
      name: "Konstantinos Tsimikas",
      position: "DEF",
      destination: "Open (Olympiacos / Galatasaray)",
      feeAsk: { min: 12, max: 16, currency: "€m" },
      probability: 52,
      heatTier: "warm",
      sources: [{ name: "Liverpool.com", tier: "B" }],
      note: "Kerkez's understudy slot belongs to academy; Tsimikas is movable.",
    },
    {
      id: "elliott-out",
      name: "Harvey Elliott",
      position: "MID",
      destination: "PL mid-table",
      feeAsk: { min: 30, max: 40, currency: "€m" },
      probability: 44,
      heatTier: "warm",
      sources: [{ name: "Sky Sports", tier: "A" }, { name: "TEAMtalk", tier: "C" }],
      note: "Wirtz's arrival closed the No. 10 ladder behind him.",
    },
    {
      id: "mamardashvili-out",
      name: "Giorgi Mamardashvili",
      position: "GK",
      destination: "Loan (likely)",
      feeAsk: { min: 0, max: 0, currency: "€" },
      probability: 55,
      heatTier: "warm",
      sources: [{ name: "Football365", tier: "B" }, { name: "Liverpool.com", tier: "B" }],
      note: "Sat 6 Jun — collateral of Alisson's U-turn: with the Brazilian snubbing Juventus to stay another year, the £29m Valencia signing recruited as his heir now looks likelier to leave on loan than serve a second season as understudy. Game time, not a sale, is the priority.",
    },
    {
      id: "ramsay-out",
      name: "Calvin Ramsay",
      position: "DEF",
      destination: "Loan / sale",
      feeAsk: { min: 4, max: 6, currency: "€m" },
      probability: 36,
      heatTier: "cool",
      sources: [{ name: "Liverpool.com", tier: "B" }],
      note: "Three years on the books, no senior minutes; the inventory clear-out.",
    },
  ],
  sources: [
    "David Ornstein",
    "Fabrizio Romano",
    "TeamTalk",
    "Football365",
    "FootballFanCast",
    "GiveMeSport",
    "This Is Anfield",
    "Liverpool.com",
    "TheHardTackle",
    "Anfield Watch",
    "Rousing The Kop",
    "Sky Sports",
    "ESPN",
    "Managing Madrid",
    "Caught Offside",
  ],
};
